apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: e27ldxn5b-go 
  janus-idp.io/tekton: e27ldxn5b-go
  backstage.io/kubernetes-id: e27ldxn5b-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e27ldxn5b-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml